### ISSUE TITLE
mac bigsur idea 2020.3

### ISSUE THREAD

**Issue by a827871781** [lachlankrautz/background_image_switch#26]
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:57)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getIcon(ToolWindowImpl.kt:386)
	at com.intellij.openapi.wm.impl.StripeButton.updatePresentation(StripeButton.java:342)
	at com.intellij.openapi.wm.impl.Stripe.updatePresentation(Stripe.java:444)
	at com.intellij.openapi.wm.impl.Stripe.uiSettingsChanged(Stripe.java:66)
	at jdk.internal.reflect.GeneratedMethodAccessor151.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:123)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:86)
	at com.sun.proxy.$Proxy42.uiSettingsChanged(Unknown Source)
	at com.intellij.ide.ui.UISettings.fireUISettingsChanged(UISettings.kt:613)
	at com.intellij.openapi.wm.impl.IdeBackgroundUtil.repaintAllWindows(IdeBackgroundUtil.java:205)
	at co.notime.intellijPlugin.backgroundImagePlus.RandomBackgroundTask.run(RandomBackgroundTask.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by empcl** [comment]
Hello, is this problem solved?
